-- -----------------------------------------------------------------------------
-- Star Wars: Imperial Assault - Skirmish
-- by Ikon
-- -----------------------------------------------------------------------------

local DEFS = require("swia-skirmish-tts/modules/common/definitions")
local STRING = require("swia-skirmish-tts/modules/common/string")

local Logger = require("swia-skirmish-tts/modules/common/logger")
local logger = Logger:create("ttadmiral", "Pink"):setState(false)

-- -----------------------------------------------------------------------------
--  Globals
-- -----------------------------------------------------------------------------

local TTA_BASE_URL = "classic.tabletopadmiral.com/imperialassault/nuc"
local TTA_HTTP_BASE_URL = "http://"..TTA_BASE_URL
local TTA_HTTPS_BASE_URL = "https://"..TTA_BASE_URL
local TTA_SEPARATOR = "ncc"

local cards = {
  [DEFS.DEPLOYMENT_CARD] = {
    [1] = "Luke Skywalker, Hero of the Rebellion",
    [2] = "Han Solo",
    [3] = "Elite Rebel Saboteur",
    [4] = "Elite Rebel Trooper",
    [5] = "Gideon Argus",
    [6] = "General Weiss",
    [7] = "Agent Blaise",
    [8] = "Elite Alliance Ranger",
    [9] = "Alliance Ranger",
    [10] = "Elite Alliance Smuggler",
    [11] = "Alliance Smuggler",
    [12] = "Elite Bantha Rider",
    [13] = "Boba Fett",
    [14] = "Bossk",
    [15] = "Captain Terro",
    [16] = "Elite Dewback Rider",
    [17] = "Chewbacca",
    [18] = "Elite AT-ST",
    [19] = "Darth Vader",
    [20] = "Diala Passil",
    [21] = "Elite E-Web Engineer",
    [22] = "E-Web Engineer",
    [23] = "Fenn Signis",
    [24] = "Gaarkhan",
    [25] = "Elite Imperial Officer",
    [26] = "Imperial Officer",
    [27] = "Jyn Odan",
    [28] = "Mak Eshka'rey",
    [29] = "Elite Nexu",
    [30] = "Nexu",
    [31] = "Probe Droid",
    [32] = "Royal Guard",
    [33] = "Elite Stormtrooper",
    [34] = "Stormtrooper",
    [35] = "Elite Trandoshan Hunter",
    [36] = "Trandoshan Hunter",
    [37] = "Dengar",
    [38] = "Elite Echo Base Trooper",
    [39] = "Echo Base Trooper",
    [40] = "General Sorin",
    [41] = "Greedo",
    [42] = "Elite Hired Gun",
    [43] = "Hired Gun",
    [44] = "IG-88",
    [45] = "Elite ISB Infiltrator",
    [46] = "ISB Infiltrator",
    [47] = "Elite Gamorrean Guard",
    [48] = "Gamorrean Guard",
    [49] = "Elite Jet Trooper",
    [50] = "Jet Trooper",
    [51] = "Onar Koma",
    [52] = "Elite Rancor",
    [53] = "Shyla Varad",
    [54] = "Vinto Hreeda",
    [55] = "Elite Weequay Pirate",
    [56] = "Weequay Pirate",
    [57] = "Kayn Somos",
    [58] = "Lando Calrissian",
    [59] = "Leia Organa",
    [60] = "Luke Skywalker, Jedi Knight",
    [61] = "Obi-Wan Kenobi",
    [62] = "C-3PO",
    [63] = "R2-D2",
    [64] = "Rebel Saboteur",
    [65] = "Rebel Trooper",
    [66] = "Elite HK Assassin Droid",
    [67] = "HK Assassin Droid",
    [68] = "Loku Kanoloa",
    [69] = "MHD-19",
    [70] = "Elite SC2-M Repulsor Tank",
    [71] = "Elite Snowtrooper",
    [72] = "Snowtrooper",
    [73] = "Verena Talos",
    [74] = "Elite Wampa",
    [75] = "Wampa",
    [76] = "Royal Guard Champion",
    [77] = "Davith Elso",
    [78] = "Murne Rin",
    [79] = "Elite Ugnaught Tinkerer",
    [80] = "Ugnaught Tinkerer",
    [81] = "Elite Wing Guard",
    [82] = "Wing Guard",
    [83] = "The Grand Inquisitor",
    [84] = "Biv Bodhrik",
    [85] = "Elite Heavy Stormtrooper",
    [86] = "Heavy Stormtrooper",
    [87] = "Saska Teft",
    [88] = "Elite Tusken Raider",
    [89] = "Tusken Raider",
    [90] = "Elite Wookiee Warrior",
    [91] = "Wookiee Warrior",
    [92] = "Zillo Technique",
    [93] = "Survivalist",
    [94] = "Smuggler's Run",
    [95] = "Beast Tamer",
    [96] = "Explosive Armaments",
    [97] = "Headhunter",
    [98] = "Feeding Frenzy",
    [99] = "Balance of the Force",
    [100] = "Devious Scheme",
    [101] = "First Strike",
    [102] = "Rebel High Command",
    [103] = "Temporary Alliance, Hired Guns",
    [104] = "Temporary Alliance, A Common Enemy",
    [105] = "Vader's Finest",
    [106] = "Punishing Strike",
    [107] = "Combat Suit",
    [108] = "The General's Ranks",
    [109] = "Prey on the Weak",
    [110] = "Last Resort",
    [111] = "Cross-Training",
    [112] = "Rule by Fear",
    [113] = "On a Diplomatic Mission",
    [114] = "Channel the Force",
    [115] = "Targeting Computer",
    [116] = "Under Duress",
    [117] = "Advanced Com Systems",
    [118] = "Fury of Kashyyyk",
    -- 119 is None
    [120] = "Jabba the Hutt",
    [121] = "Black Market",
    [122] = "Heroic Effort",
    [123] = "Elite Probe Droid",
    [124] = "Indentured Jester",
    [125] = "Elite Royal Guard",
    [126] = "Unshakable",
    -- 127 is Salacious
    [128] = "Motivation",
    [129] = "Hera Syndulla",
    [130] = "Scavenged Weaponry",
    [131] = "BT-1",
    [132] = "C1-10P",
    [133] = "0-0-0",
    [134] = "Jawa Scavenger",
    [135] = "Focused on the Kill",
    [136] = "Elite Jawa Scavenger",
    [138] = "Ko-Tun Feralo",
    -- 137 is missing
    [139] = "Driven by Hatred",
    [140] = "Maul",
    [141] = "Emperor Palpatine",
    [142] = "Ahsoka Tano",
    [143] = "Trusted Ally",
    [144] = "Elite AT-DP",
    [145] = "Sentry Droid",
    [146] = "Clawdite Shapeshifter",
    [147] = "Drokkatta",
    [148] = "Jarrod Kelvin",
    [149] = "Rogue Smuggler",
    [150] = "Wookiee Avenger",
    [151] = "Riot Trooper",
    [152] = "Elite Clawdite Shapeshifter",
    [153] = "Elite Riot Trooper",
    [154] = "Elite Sentry Droid",
    -- 155 is missing
    -- 156 is J4X
    [157] = "Zeb Orrelios",
    [158] = "Tress Hacnua",
    [159] = "Elite Loth-cat",
    [160] = "Loth-cat",
    [161] = "CT-1701",
    [162] = "Death Trooper",
    [163] = "Elite Death Trooper",
    [164] = "Kanan Jarrus",
    [165] = "Ezra Bridger",
    [166] = "Doubt",
    [167] = "Sabine Wren",
    -- 168 is missing
    [169] = "Extra Armor",
    [170] = "Hondo Ohnaka",
    [171] = "Lie in Ambush",
    [172] = "Spectre Cell",
    [173] = "Thrawn",
    [174] = "Heavy Fire",
    [175] = "Ahsoka Tano - IACP",
    [176] = "BT-1 - IACP",
    [177] = "Diala Passil - IACP",
    [178] = "Elite Echo Base Trooper - IACP",
    [179] = "Elite Gamorrean Guard - IACP",
    [180] = "Kanan Jarrus - IACP",
    [181] = "Kayn Somos - IACP",
    [182] = "Ko-Tun Feralo - IACP",
    [183] = "Leia Organa - IACP",
    [184] = "Luke Skywalker, Hero of the Rebellion - IACP",
    [185] = "Luke Skywalker, Jedi Knight - IACP",
    [186] = "Maul - IACP",
    [187] = "Elite Probe Droid - IACP",
    [188] = "Elite Rancor - IACP",
    [189] = "Elite Rebel Trooper - IACP",
    [190] = "Elite Sentry Droid - IACP",
    [191] = "Shyla Varad - IACP",
    [192] = "Elite Stormtrooper - IACP",
    [193] = "The Grand Inquisitor - IACP",
    [194] = "Elite Wing Guard - IACP",
    [195] = "Elite Wookiee Warrior - IACP",
    [196] = "Advanced Com Systems - IACP",
    [197] = "Elite AT-ST - IACP",
    [198] = "Boba Fett - IACP",
    -- 199 is missing
    -- 200 is missing
    [201] = "Fenn Signis - IACP",
    [202] = "Gaarkhan - IACP",
    [203] = "General Weiss - IACP",
    [204] = "Imperial Retrofitting - IACP",
    [205] = "Jyn Odan - IACP",
    -- 206 is missing
    [207] = "Royal Guard Champion - IACP",
    [208] = "Suppressive Fire - IACP",
    [209] = "4-LOM - IACP",
    [210] = "Biv Bodhrik - IACP",
    [211] = "Dengar - IACP",
    [212] = "Zuckuss - IACP",
    [213] = "Fury of Kashyyyk - IACP",
    [214] = "Obi-Wan Kenobi - IACP",
    [215] = "Elite Royal Guard - IACP",
    [216] = "Saska Teft - IACP",
    [217] = "Elite SC2-M Repulsor Tank - IACP",
    [218] = "Elite Scout Trooper - IACP",
    [219] = "Yoda - IACP",
    [220] = "Elite Tusken Raider - IACP",
    [221] = "Elite ISB Infiltrator - IACP",
    [222] = "Agent Blaise - IACP",
    [223] = "Elite AT-RT - IACP",
    [224] = "Bossk - IACP",
    [225] = "Jyn Erso - IACP",
    [226] = "Director Krennic - IACP",
    [227] = "IG-11 - IACP",
    [228] = "The Mandalorian, Renegade Hunter - IACP",
    [229] = "The Child - IACP",
    [230] = "Clan of Two - IACP",
    [231] = "Elite E-Web Engineer - IACP",
    [232] = "General Sorin - IACP",
    [233] = "Lando Calrissian - IACP",
    [234] = "Loku Kanoloa - IACP",
    [235] = "Elite Shoretrooper - IACP",
    [236] = "Elite Mortar Trooper - IACP",
    [237] = "Overwatch - IACP",
    [238] = "Elite Rebel Pathfinder - IACP",
    [239] = "Elite Rebel Saboteur - IACP",
    [240] = "The Darksaber - IACP",
    [241] = "Elite Trandoshan Hunter - IACP",
    [242] = "Verena Talos - IACP",
    [243] = "Agent Kallus - IACP",
    [244] = "Captain Terro - IACP",
    [245] = "Cassian Andor - IACP",
    [246] = "Elite Clawdite Shapeshifter",  -- IACP eClaw then removed
    [247] = "Davith Elso - IACP",
    [248] = "Doctor Aphra - IACP",
    [249] = "Elite Heavy Stormtrooper - IACP",
    [250] = "HK-47 - IACP",
    [251] = "Iden Versio - IACP",
    [252] = "K-2SO - IACP",
    [253] = "Luke Skywalker, Jedi Knight - IACP",
    [254] = "Mara Jade - IACP",
    [255] = "Murne Rin - IACP",
    [256] = "Elite Wampa - IACP",
    [257] = "Fury of Kashyyyk - IACP",
    [258] = "The General's Ranks - IACP",
    [259] = "Under Duress - IACP",
    [260] = "Cara Dune - IACP",
    [261] = "Bib Fortuna - IACP",
    [262] = "CT-1701 - IACP",
    [263] = "Elite Dark Trooper Mk III - IACP",
    [264] = "Elite Dewback Rider - IACP",
    [265] = "First Strike - IACP",
    [266] = "Elite Flametrooper - IACP",
    [267] = "Migs Mayfeld - IACP",
    [268] = "Moff Gideon - IACP",
    [269] = "Elite Snowtrooper - IACP",
    [270] = "Elite Z-6 Trooper - IACP",
    [271] = "The Mandalorian, Rising Phoenix - IACP",
  },
  [DEFS.COMMAND_CARD] = {
    [1] = "Heart of Freedom",
    [2] = "Self-Defense",
    -- 3 is missing
    [4] = "Espionage Mastery",
    [5] = "Intelligence Leak",
    [6] = "Smuggled Supplies",
    [7] = "Smugglers Tricks",
    [8] = "Crush",
    [9] = "Jundland Terror",
    [10] = "Opportunistic",
    [11] = "Parting Blow",
    [12] = "Capture the Weary",
    [13] = "Mandalorian Tactics",
    [14] = "Disorient",
    [15] = "Grisly Contest",
    [16] = "Trandoshan Terror",
    [17] = "Adrenaline",
    [18] = "Debts Repaid",
    [19] = "Hold Ground",
    [20] = "Roar",
    [21] = "Wookiee Rage",
    [22] = "Burst Fire",
    [23] = "Celebration",
    [24] = "Close the Gap",
    [25] = "Covering Fire",
    [26] = "Deadeye",
    [27] = "Deflection",
    [28] = "Element of Surprise",
    [29] = "Expose Weakness",
    [30] = "Ferocity",
    [31] = "Fleet Footed",
    [32] = "Force Lightning",
    [33] = "Furious Charge",
    [34] = "Guardian Stance",
    [35] = "Hunter Protocol",
    [36] = "Knowledge and Defense",
    [37] = "Lord of the Sith",
    [38] = "Lure of the Dark Side",
    [39] = "Marksman",
    [40] = "Maximum Firepower",
    [41] = "Meditation",
    [42] = "One in a Million",
    [43] = "Planning",
    [44] = "Price on Their Heads",
    [45] = "Pummel",
    [46] = "Rally",
    [47] = "Recovery",
    [48] = "Regroup",
    [49] = "Shadow Ops",
    [50] = "Sit Tight",
    [51] = "Son of Skywalker",
    [52] = "Take Cover",
    [53] = "Take Initiative",
    [54] = "Take it Down",
    [55] = "Telekinetic Throw",
    [56] = "To the Limit",
    [57] = "Urgency",
    [58] = "Brace Yourself",
    [59] = "Dangerous Bargains",
    [60] = "Payback",
    [61] = "Against the Odds",
    [62] = "Efficient Travel",
    [63] = "Hit and Run",
    [64] = "Field Tactician",
    [65] = "Fuel Upgrade",
    [66] = "Optimal Bombardment",
    [67] = "Endless Reserves",
    [68] = "Explosive Weaponry",
    [69] = "Heavy Armor",
    [70] = "New Orders",
    [71] = "Overrun",
    [72] = "In the Shadows",
    [73] = "Primary Target",
    [74] = "Stroke of Brilliance",
    [75] = "Disable",
    [76] = "I Make My Own Luck",
    [77] = "Inspiring Speech",
    [78] = "Reposition",
    [79] = "Slippery Target",
    [80] = "Of No Importance",
    [81] = "Blaze of Glory",
    [82] = "Dirty Trick",
    [83] = "Merciless",
    [84] = "Overdrive",
    [85] = "Repair",
    [86] = "Comm Disruption",
    [87] = "Data Theft",
    [88] = "Strategic Shift",
    [89] = "Rally the Troops",
    [90] = "Rank and File",
    [91] = "Squad Swarm",
    [92] = "Black Market Prices",
    [93] = "Cheat to Win",
    [94] = "Stall for Time",
    [95] = "Behind Enemy Lines",
    [96] = "I Can Feel It",
    [97] = "There is Another",
    [98] = "A Powerful Influence",
    [99] = "Force Surge",
    [100] = "I Must Go Alone",
    [101] = "Devotion",
    [102] = "Etiquette and Protocol",
    [103] = "Hard to Hit",
    [104] = "Single Purpose",
    [105] = "Terminal Network",
    [106] = "Change of Plans",
    [107] = "Collect Intel",
    [108] = "Emergency Aid",
    [109] = "Hide in Plain Sight",
    [110] = "Lock On",
    [111] = "Focus",
    [112] = "Grenadier",
    [113] = "Reinforcements",
    [114] = "Strength in Numbers",
    [115] = "Coordinated Attack",
    [116] = "Harsh Environment",
    [117] = "Master Operative",
    [118] = "Miracle Worker",
    [119] = "Negation",
    [120] = "Overcharged Weapons",
    [121] = "Set a Trap",
    [122] = "Size Advantage",
    [123] = "Survival Instincts",
    [124] = "Bodyguard",
    [125] = "Counter Attack",
    [126] = "Cripple",
    [127] = "Flurry of Blades",
    [128] = "Set for Stun",
    [129] = "Stealth Tactics",
    [130] = "Camouflage",
    [131] = "Fatal Deception",
    [132] = "Force Illusion",
    [133] = "Vanish",
    [134] = "Deadly Precision",
    [135] = "Force Rush",
    [136] = "Hunt Them Down",
    [137] = "Cruel Strike",
    [138] = "Hidden Trap",
    [139] = "Stay Down",
    [140] = "Improvised Weapons",
    [141] = "Wild Fury",
    [142] = "Shoot the Messenger",
    [143] = "Assassinate",
    [144] = "Blood Feud",
    [145] = "Jump Jets",
    [146] = "Tough Luck",
    [147] = "Wild Attack",
    [148] = "Call the Vanguard",
    [149] = "Heightened Reflexes",
    [150] = "Mitigate",
    [151] = "Battlefield Awareness",
    [152] = "Cavalry Charge",
    [153] = "Feral Swipes",
    [154] = "Blitz",
    [155] = "Parry",
    [156] = "Positioning Advantage",
    [157] = "On the Lam",
    [158] = "Tools for the Job",
    [159] = "Stimulants",
    [160] = "Pickpocket",
    [161] = "Toxic Dart",
    [162] = "Glory of the Kill",
    [163] = "Run for Cover",
    [164] = "Draw!",
    [165] = "Extra Protection",
    [166] = "Bladestorm",
    [167] = "Sarlacc Sweep",
    [168] = "Provoke",
    [169] = "Shared Experience",
    [170] = "Ballistics Matrix",
    [171] = "Triangulate",
    [172] = "On a Mission",
    [173] = "Shared Experience",
    [174] = "Eerie Visage",
    [175] = "Utinni!",
    [176] = "Navigation Upgrade",
    [177] = "Advance Warning",
    [178] = "Targeting Network",
    [179] = "Evacuate",
    [180] = "Looking for a Fight",
    [181] = "Cut Lines",
    [182] = "Brace for Impact",
    [183] = "Take Position",
    [184] = "Battle Scars",
    [185] = "Collateral Damage",
    [186] = "Field Supply",
    [187] = "Heavy Ordnance",
    [188] = "Ready Weapons",
    [189] = "Terminal Protocol",
    [190] = "Take Position",
    [191] = "Balancing Force",
    [192] = "Fool Me Once",
    [193] = "Force Jump",
    [194] = "Force Push",
    [195] = "Right Back At Ya!",
    [196] = "Chaotic Force",
    [197] = "Deathblow",
    [198] = "Face to Face",
    [199] = "Looking for a Fight",
    [200] = "Wreak Vengeance",
    [201] = "Corrupting Force",
    [202] = "Dark Energy",
    [203] = "Prepared for Battle",
    [204] = "Unlimited Power",
    [205] = "Arcing Shot",
    [206] = "Armed Escort",
    [207] = "Concentrated Fire",
    [208] = "Droid Mastery",
    [209] = "Forward March",
    [210] = "Officer's Training",
    [211] = "Spinning Kick",
    [212] = "Wild Fire",
    [213] = "Signal Jammer",
    [214] = "Second Chance",
    [215] = "Protect the Old Ways",
    [216] = "Learn by Example",
    [217] = "Hour of Need",
    [218] = "Dying Lunge",
    [219] = "Karabast",
    [220] = "Rebel Graffiti",
    [221] = "Veteran Instincts",
    [222] = "Hostile Negotiation",
    [223] = "Let's Make a Deal",
    [224] = "Out of Time",
    [225] = "Worth Every Credit",
    [226] = "Marked Territory",
    [227] = "Pack Alpha",
    [228] = "Induce Rage",
    [229] = "Price of Glory",
    [230] = "Foresee",
    [231] = "Combat Resupply",
    [232] = "Escalating Hostility",
    [233] = "Assassinate - IACP",
    -- 234 is missing
    [235] = "On the Lam - IACP",
    [236] = "Deflection - IACP",
    -- 237 is missing
    [238] = "Mandalorian Tactics - IACP",
    [239] = "Knowledge and Defense - IACP",
    [240] = "Close and Personal - IACP",
    [241] = "Findsman Meditation - IACP",
    [242] = "Get Behind Me! - IACP",
    [243] = "Parry - IACP",
    [244] = "Preservation Protocol - IACP",
    -- 245 is missing
    [246] = "There Is No Try - IACP",
    [247] = "Iron Will - IACP",
    [248] = "Built on Hope - IACP",
    [249] = "Deploy the Garrison! - IACP",
    [250] = "Guild Programming - IACP",
    [251] = "Whistling Birds - IACP",
    [252] = "Apex Predator - IACP",
    [253] = "Blend In - IACP",
    [254] = "Cavalry Charge - IACP",
    [255] = "Definition: 'Love' - IACP",
    [256] = "Face Me! - IACP",
    [257] = "Feint - IACP",
    [258] = "Overwhelming Impact - IACP",
    [259] = "Rapid Recalibration - IACP",
    [260] = "Reactive Loyalties - IACP",
    [261] = "Rest in Peace - IACP",
    [262] = "Sniper Configuration - IACP",
    [263] = "Static Pulse - IACP",
    [264] = "Windfall - IACP",
    -- 265 is missing
    [266] = "Ambush - IACP",
    [267] = "Covering Fire - IACP",
    [268] = "Expose Weakness - IACP",
    [269] = "Honoring the Fallen - IACP",
    [270] = "Demoralizing Monologue - IACP",
    [271] = "Palace Politics - IACP",
  }
}

-- -----------------------------------------------------------------------------
-- Utilities
-- -----------------------------------------------------------------------------

local function isValidUrl(url)
  return url:find(TTA_HTTP_BASE_URL) == 1 or url:find(TTA_HTTPS_BASE_URL) == 1
end

local function tocardid(str)
  if str then
    local id = tonumber(str)
    if id > 0 then
      return id
    end
  end
  return nil
end

local function getDecks(url)
  if not isValidUrl(url) then
    return nil
  end
  url = string.gsub(url, TTA_HTTP_BASE_URL, "")
  url = string.gsub(url, TTA_HTTPS_BASE_URL, "")
  local codes = STRING.splitChr(url, TTA_SEPARATOR)
  if #codes ~= 2 then
    return nil
  end
  local result = {}
  result[DEFS.DEPLOYMENT_CARD] = STRING.splitNth(codes[1], 3, tocardid)
  result[DEFS.COMMAND_CARD] = STRING.splitNth(codes[2], 3, tocardid)
  return result
end

-- -----------------------------------------------------------------------------
-- Tabletop Admiral
-- -----------------------------------------------------------------------------

local m = {}

function m.getArmy(url)
  logger:debug({url}, "ttadmiral:getArmy")
  local decks = getDecks(url)
  local result = nil
  if decks then
    result = {}
    for cardType, codes in pairs(decks) do
      result[cardType] = {}
      for _, code in pairs(codes) do
        local card = cards[cardType][code]
        if card ~= nil then
          table.insert(result[cardType], card)
        end
      end
    end
  end
  return result
end

return m
